### ISSUE TITLE
Create a program or project in any programming language of your choice that you would enjoy working with.

### ISSUE THREAD

**Issue by simranlotey** [simranlotey/Hacktoberfest#379]
Create a program or project in any programming language of your choice that you would enjoy working with.

**Comment by mishrayush15** [comment]
Hey Buddy! I have a very great idea of creating my own CLI based Pokemon Game using JAVA. Could you please assign this task to me.

**Comment by simranlotey** [comment]
> Hey Buddy! I have a very great idea of creating my own CLI based Pokemon Game using JAVA. Could you please assign this task to me

Sure! @mishrayush15 let's do it ;)

**Comment by eeshan15** [comment]
Hello @simranlotey I also want to Contribute for the hactoberfest2024 challenge can you help and tell what to do I have read the readme file but if you can simplify a bit it would be great.

**Comment by simranlotey** [comment]
Sure! @eeshan15 Build a Command-Line Quiz Application that presents users with multiple-choice questions and tracks their scores. Allow users to choose categories and difficulty levels, and provide immediate feedback on their answers. Save user scores and questions in a local JSON file for future reference.

**Comment by eeshan15** [comment]
@simranlotey thanks for assigning mate so do I have to make a new branch and after review will it be merged?

**Comment by simranlotey** [comment]
yes @eeshan15

**Comment by nikkvijay** [comment]
Hello Sir, just checking in! Do you have any issues or ideas you’d like to discuss? Let me know!

**Comment by simranlotey** [comment]
Hii @nikkvijay  Build a Command-Line Quiz Application that presents users with multiple-choice questions and tracks their scores. Allow users to choose categories and difficulty levels, and provide immediate feedback on their answers. Save user scores and questions in a local JSON file for future reference.

**Comment by nikkvijay** [comment]
I’ll get started on this.

**Comment by Nituhimani** [comment]
Hii..I want to make a chatbot which takes users data in form of pdf and gives us answer from the pdf. Please assign this to me

**Comment by simranlotey** [comment]
I assigned you @Nituhimani

**Comment by rohansen856** [comment]
Hi, @simranlotey i would like to add a project it rust langunage: It will be a cli based "connect dots game" (https://en.wikipedia.org/wiki/Connect_Four). Can i work on this project?

**Comment by simranlotey** [comment]
Sure! @rohansen856

**Comment by anill1412** [comment]
Hello @simranlotey I also want to Contribute for the hactoberfest2024 challenge.
can you assign this to me

**Comment by Khushi-Sarawagi** [comment]
Hey @simranlotey , I want to contribute for the hacktoberfest , could you assign this to me?

**Comment by princyballabh** [comment]
@simranlotey Hey!... I am adding a few programs in Java

**Comment by princyballabh** [comment]
@simranlotey I have made a PR. Please do check it out.
