### ISSUE TITLE
Add Guess the States of India: A Learning Game using Python

### ISSUE THREAD

**Issue by SyedShagufta** [simranlotey/Hacktoberfest#397]
Title: "Guess the States of India: A Learning Game"

Description:
- This Python-based game challenges users to test their knowledge of India's states. 
- The game prompts players to guess all the states, providing an engaging and educational way to learn or refresh their memory about India's geography.
-  if you are curious about how many states you know, this game offers a fun and interactive experience!
- You will be able to see the score of correct states you states out of the number of states

could you please assign it to me under #Hacktoberfest2024. Thank You.

**Comment by guptushar27** [comment]
kindly please assign this to me
