### ISSUE TITLE
Request to check hacktoberfest tag

### ISSUE THREAD

**Issue by vidhirohira** [simranlotey/Hacktoberfest#410]
I tried to submit a pull request to your repository, but I found that it’s marked as excluded on the Hacktoberfest website, despite having the Hacktoberfest tag on GitHub. Could you please look into this? I appreciate your understanding.

Thank you!

**Comment by simranlotey** [comment]
Hey! @vidhirohira Apologies for the inconvenience. I'll check on this and get it sorted.
